const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#5C6B4A",
    background: "#FFFFFF",
    foreground: "#0a0a0a",
    card: "#F5F5F5",
    cardForeground: "#0a0a0a",
    primary: "#5C6B4A",
    primaryForeground: "#FFFFFF",
    secondary: "#E5E5E5",
    secondaryForeground: "#1a1a1a",
    muted: "#E5E5E5",
    mutedForeground: "#737373",
    accent: "#5C6B4A",
    accentForeground: "#FFFFFF",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#E0E0E0",
    input: "#E0E0E0",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#7A8C68",
    background: "#0A0A0A",
    foreground: "#FFFFFF",
    card: "#1C1C1E",
    cardForeground: "#FFFFFF",
    primary: "#6B7B5A",
    primaryForeground: "#FFFFFF",
    secondary: "#2C2C2E",
    secondaryForeground: "#AEAEB2",
    muted: "#2C2C2E",
    mutedForeground: "#8E8E93",
    accent: "#5C6B4A",
    accentForeground: "#FFFFFF",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#2C2C2E",
    input: "#2C2C2E",
  },
  radius: 12,
};

export default colors;
